version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: authserviceYourVoice_postgres
    restart: always
    environment:
      POSTGRES_DB: DBYourVoice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
     - "5454:5432"
    volumes:
      - postgres_data_yourvoice:/var/lib/postgresql/data

volumes:
  postgres_data_yourvoice:
